# # AUTOGENERATED! DO NOT EDIT! File to edit: src/attribute.ipynb (unless otherwise specified).

__all__ = ['Attribute']

from enum import Enum

# Cell
class Attribute(Enum):
     TYPE_NOMINAL = 1
     TYPE_NUMERICAL = 2
