# AUTOGENERATED! DO NOT EDIT! File to edit: src/parse_exception.ipynb (unless otherwise specified).

__all__ = ['ParseException']

# Cell
class ParseException(Exception):
    def __init__(self, m: str):
        super().__init__(m)
