# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AttStats": "att_stats.ipynb",
         "Attribute": "attribute.ipynb",
         "Data": "data.ipynb",
         "DataScrambler": "data_scrambler.ipynb",
         "EntropyEvaluator": "entropy_evaluator.ipynb",
         "Instance": "instance.ipynb",
         "ParseException": "parse_exception.ipynb",
         "Reading": "reading.ipynb",
         "Tree": "tree.ipynb",
         "TreeEdge": "tree_edge.ipynb",
         "TreeEvaluator": "tree_evaluator.ipynb",
         "TreeNode": "tree_node.ipynb",
         "UId3": "uId3.ipynb",
         "UncertainEntropyEvaluator": "uncertain_entropy_evaluator.ipynb",
         "Value": "value.ipynb"}

modules = ["att_stats.py",
           "attribute.py",
           "data.py",
           "data_scrambler.py",
           "entropy_evaluator.py",
           "instance.py",
           "parse_exception.py",
           "reading.py",
           "tree.py",
           "tree_edge.py",
           "tree_evaluator.py",
           "tree_node.py",
           "uid3.py",
           "uncertain_entropy_evaluator.py",
           "value.py"]

doc_url = "//pyuid3"

git_url = "https://gitlab.com/geist-stud/pyuid3/tree/master/"

def custom_doc_links(name): return None
