# AUTOGENERATED! DO NOT EDIT! File to edit: src/tree_edge.ipynb (unless otherwise specified).

__all__ = ['TreeEdge']

# Cell
from .value import Value
from .tree_node import TreeNode

# Cell
class TreeEdge:
    def __init__(self, value: Value, child: 'TreeNode'):
        self.value = value
        self.child = child

    def get_value(self) -> Value:
        return self.value

    def get_child(self) -> 'TreeNode':
        return self.child
    
    def copy(self):
        return type(self)(self.value, self.child.copy())
